menu = {'hamburguesa': 1, 
        'Sandwiches de pollo': 1, 
        'Papas y complementos': 1, 
        'Bebidas': 1, 
        'Postres': 1, 
        'Ensaladas': 1, 
        'Mc Café': 1, 
        'Cajita Feliz': 1, 
        'Armar tu combo personalizado': None, 
        'Salir': None}

hamburguesa = {'Hamburguesa simple':1000, 
               'Hamburguesa con Queso':1, 
               'McFiesta':1, 
               'Doble Carne Doble Queso':1, 
               'Triple Hamburguesa con Queso':1, 
               'Big Mac':1, 
               'Cuarto de Libra con Queso':1, 
               'McNitica': 1, 
               'Dobñe Cuarto de Libra con Queso': 1, 
               'Hamburguesa (Cajita Feliz)':1, 
               'McFiesta Jr. (Cajita Feliz)':1, 
               'Grand Tasty Doble':1, 
               'Grand Tasty Triple':1, 
               'Grand Doble McBacon':1, 
               'Grand Triple McBacon':1, 
               'Grand Tasty Turbo Bacon Doble':1}

sandwich_pollo = {'McPollo': 1, 
                  'McCrispy Chicken Deluxe': 1, 
                  'McCrispy Chicken Deluxe Spicy': 1, 
                  'McCrispy Chicken Cheddar & Bacon': 1, 
                  'McCrispy Chicken Smoked BBQ': 1, 
                  'McNuggets 4 unidades': 1, 
                  'McNuggets 6 unidades': 1, 
                  'McNuggets 10 unidades': 1, 
                  'McNuggets 20 unidades': 1, 
                  'McCrispy Chicken Classic': 1, 
                  'Cancelar Pedido': 1}

papas_complementos = {'Papas Grandes': 1, 
                      'Papas Medianas': 1, 
                      'Papas Pequeñas': 1, 
                      'Papas Kids': 1, 
                      'Side Salad': 1, 
                      'Papas con cheddar y bacon': 1, 
                      'Papas con tasty y bacon': 1, 
                      'Papas con tasty': 1, 
                      'Papas con cheddar': 1}

bebidas = {'Agua sin gas (500ml)': 1, 
           'Coca Cola Chica': 1, 
           'Coca Cola Mediana': 1, 
           'Coca Cola Grande': 1, 
           'Coca Cola Light Chica': 1, 
           'Coca Cola Light Mediana': 1, 
           'Coca Cola Light Grande': 1, 
           'Coca Cola Zero Chica': 1, 
           'Coca Cola Zero Mediana': 1, 
           'Coca Cola Zero Grande': 1, 
           'Fanta Chica Fanta Mediana': 1, 
           'Fanta Grande Sprite Zero': 1, 
           'Chica Sprite Zero Mediana': 1, 
           'Sprite Zero Grande': 1, 
           'Jugo de Manzana': 1,}

postres = {'Cono de Vainilla': 1, 
           'Cono Combinado': 1, 
           'Cono de Dulce de Leche': 1, 
           'Super Cono': 1, 
           'Cono Relleno': 1, 
           'Cono Kit Kat': 1, 
           'Sundae de Dulce de Leche': 1, 
           'Sundae de Chocolate': 1, 
           'Sundae de Frutilla': 1, 
           'McFlurry Oreo': 1, 
           'McFlurry Kit Kat': 1, 
           'YogurKid': 1, 
           'Mc Flurry Crocantella': 1, 
           'Sundae Crocantella': 1}

ensaladas = {'Ensalada Deli Fresh con pollo grille': 1, 
             'Ensalada Deli Fresh con pollo crispy': 1, 
             'Ensalada Deli Fresh veggie': 1}

mc_café = {"Café Americano": 1, 
           "Latte Americano": 1, 
           "Lagrima Americano": 1, 
           "Cappuccino Americano": 1, 
           "Cortado Espresso": 1, 
           "Macchiato Espresso": 1, 
           "Macchiato Bombon Espresso": 1, 
           "Espresso Doble": 1, 
           "Lágrima Espresso": 1, 
           "Latte Espresso": 1, 
           "Vainilla Latte Espresso": 1, 
           "Cappuccino Espresso": 1, 
           "Cappuccino Mocca Espresso": 1, 
           "Cappuccino Tentacion Espresso": 1, 
           "Cappuccino Bombón Espresso": 1, 
           "Cappuccino Croccantella Espresso": 1, 
           "Snack Saludable Semilla de Girasol y Arándanos": 1, 
           "Poundcake Devil's Cake": 1, 
           "Poundcake de Naranja": 1, 
           "Poundcake de Banana con Nuez": 1, 
           "Alfajor de Maicena": 1, 
           "Facturas": 1, 
           "Donut": 1, 
           "Tostado de lomo y Queso": 1, 
           "Sándwich con Bacon, Queso y Huevo": 1, 
           "Sándwich con Lomo, Queso y Huevo": 1, 
           "Medialuna de Grasa": 1, 
           "Croissant de Chocolate": 1, 
           "Pan de Queso": 1, 
           "Medialuna de Lomito y Queso": 1, 
           "Cheescake": 1, 
           "Crumble Manzana": 1, 
           "Torta Argentina": 1, 
           "Cake de Chocolate": 1, 
           "Calzone Espinaca con Hongos y Queso": 1, 
           "Sándwich Lomo Napolitano": 1, 
           "Sándwich Pollo Napolitano": 1, 
           "Submarino": 1, 
           "Té": 1, 
           "Agua Frutada Power Day": 1, 
           "Agua Frutada Chill Day": 1, 
           "Milkshake Frutilla": 1, 
           "Milkshake Vainilla": 1, 
           "Milkshake DDL": 1, 
           "Milkshake Chocolate": 1, 
           "Milkshake Oreo": 1, 
           "Milkshake Croccantella": 1, 
           "Chocolatada Croccantella": 1, 
           "Iced Latte": 1, 
           "Iced Vainilla Latte": 1, 
           "Iced Coffee": 1, 
           "Iced Machiatto": 1, 
           "Frappe Dulce de Leche": 1, 
           "Frappé Oreo": 1, 
           "Frappé Mocca": 1, 
           "Frappe Frutos Rojos": 1, 
           "Frappé Limonada": 1, 
           "Frappé Frutilla y Banana": 1}

cajita_feliz = {'McNuggets 4 unidades': 1, 
                'Hamburguesa (Cajita Feliz)': 1, 
                'McFiesta Jr. (Cajita Feliz)': 1, 
                'Papas Kids': 1, 
                'Agua sin gas (500ml)': 1, 
                'Jugo de Manzana': 1, 
                'YogurKid': 1}